name: Deploy to Production

on:
  push:
    branches:
      -master

jobs:

  prepare-prod-deployment:
    name: Deploy to Production
    runs-on: ubuntu-latest
    timeout-minutes: 85
    steps:

      - name: Request Deployment from BR Cloud
        id: deploy-prod
        run: |
          echo $$(git describe --tags --match rc).tar.gz
