name: Deploy to UAT and Git Tag (v2)

on:
  push:
    branches:
      - geoff-test

jobs:
  build:
    name: Build Master
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:

      #
      # Step 1
      #
      - name: Checkout
        run: |
          mkdir target
          cd target && touch website-v3.0.857-23-gc5cf9e9dd-distribution.tar.gz


      #
      # upload build for next job
      #
      - name: Store Artifact for Later in the Pipeline
        uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: target/*.tar.gz
          if-no-files-found: error


  ODv1Deployment:
    name: Deploy to ODv1
    needs: build
    runs-on: ubuntu-latest
    env:
      ENV: "uat"
    steps:


      #
      # Download the distribution artifact
      #
      - name: Download version artifact
        uses: actions/download-artifact@v2
        id: download

      - name: Get artifact details
        id: details
        run: |
          pwd
          ls
          build=$(echo ls *.tar.gz | awk '{ print $2 }')
          version=$(echo ls *.tar.gz | awk '{ print $2 }' | grep -oP '(?<=website-).*(?=-distribution.tar.gz)')
          echo "::set-output name=build::${build}"
          echo "::set-output name=version::${version}"
        working-directory: ${{steps.download.outputs.download-path}}/distribution

      #
      # Upload the distribution to RD
      #
      - name: Upload distribution
        run: |
          ls
          echo put ${{ env.BUILD }} /uploads/dists/${{ env.VERSION }}.tar.gz | sftp nhs@static.hosting.onehippo.com
        env:
          BUILD: ${{steps.details.output.build}}
          VERSION: ${{steps.details.output.version}}
        working-directory: ${{steps.download.outputs.download-path}}/distribution