name: Deploy to UAT and Git Tag (v2)

on:
  push:
    branches:
      - master

jobs:
  CalcVersion:
    name: Update Distribution Version Number
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      ENV: uat

    steps:

      #
      # Step 1
      #
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #
      # Step 2
      #
      - name: Fetch Tags
        run: |
          git tag -l | xargs git tag -d
          git fetch -t

      #
      # Step 3
      #
      - name: Bump the version number
        run: make version.bumpup

      #
      # Step 4
      #
      - name: Set the commit's Git status
        run: make github.status.success

      #
      # Step 5
      #
      - name: Push tag back to github
        run: |
          make git.update-environment-tag
          git push --tags
