name: Deploy to UAT and Git Tag (v2)

on:
  push:
    branches:
      - master

jobs:
  CalcVersion:
    name: Update Distribution Version Number
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      ENV: uat

    steps:

      #
      # Step 1
      #
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #
      # Step 2
      #
      - name: Fetch Tags
        run: |
          git fetch --tags
          git describe --abbrev=0 --tags --match "v3.0.*" | perl -pe 's/^(v(\d+\.)*)(-?\d+)(.*)$/$1.($3+1).$4/e'


      #
      # Step 3
      #
      #- name: Bump the version number
      #  run: make version.bumpup

      #
      # Step 4
      #
      - name: Set the commit's Git status
        run: make github.status.success

      #
      # Step 5
      #
      - name: Push tag back to github
        run: |
          make git.update-environment-tag
          git push --tags
