name: Deploy to UAT and Git Tag (v2)

on:
  push:
    branches:
      - master

jobs:
  CalcVersion:
    name: Update Distribution Version Number
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      ENV: uat

    steps:

      #
      # Step 1
      #
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Version Calculator
        id: version
        run: |
          git tag -l | xargs git tag -d
          git fetch -t
          version=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1) --match "v3.0.*" | perl -pe 's/^(v(\d+\.)*)(-?\d+)(.*)$/$1.($3+1).$4/e')
          echo "::set-output name=version::$version"




      #
      # Step 3
      #
      - name: Bump the version number
        run: |
          git tag ${{ env.VERSION }}
        env:
          VERSION: ${{ steps.version.outputs.version }}

      #
      # Step 4
      #
      #- name: Set the commit's Git status
      #  run: make github.status.success

      - name: Bump the version number
        run: make version.bumpup

      - name: Push tag back to github
        run: |
          make git.update-environment-tag
          git push --tags
          echo "Pushed"