name: Prepare for next day deployment

on:
  push:
    branches:
      - master

jobs:

  prepare-prod-deployment:
    name: Prepare for next day deployment
    runs-on: ubuntu-latest
    timeout-minutes: 85
    steps:

      #
      # Step 1
      #
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Need all the tags for versioning

      - name: Tagging the build
        run: |
          make git.update-environment-tag ENV=prd VERSION=v3.0.1013  &&
          make git.update-environment-tag ENV=rc VERSION=uat
          git log --format="* %s. [Author %an]" prd..rc


