name: Prepare for next day deployment

on:
  push:
    branches:
      - master

jobs:

  prepare-prod-deployment:
    name: Prepare for next day deployment
    runs-on: ubuntu-latest
    timeout-minutes: 85
    steps:
      - name: Configure SSH certificates
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.IDM_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.IDM_PUB }}" > ~/.ssh/id_rsa.pub
          chmod 400 ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa.pub
      - name: Configure known hosts
        run: |
          touch ~/.ssh/known_hosts
          echo "1"
          ssh-keygen -R ${{ secrets.RD_FTP }}
          echo "2"
          ssh-keyscan -H -t rsa ${{ secrets.RD_FTP }} >> ~/.ssh/known_hosts
          echo "3"
      - name: Tagging the build
        run: |
            git log --format="* %s. [Author %an]" prd..rc



