name: Prepare for next day deployment

on:
  schedule:
    # Runs at 3 pm weekdays (UK time)
    - cron: "*/5 * * * *"

jobs:

  prepare-prod-deployment:
    name: Prepare for next day deployment
    runs-on: ubuntu-latest
    timeout-minutes: 85
    steps:

      - name: Show default environment variables
        run: |
          echo "The job_id is: "
      - name: Checkout (check this)
        id: githublist
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Need all the tags for versioning
          run: |
            echo "Deven-<<>>>->"

      - name: Slack message (List Jira Tickets to be released)
        if: ${{ success() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "C04KERNBD4J", "text": "Release to production has been scheduled at 12:05 on the next working day. The following new changes (if any) will be released:", "attachments": [{ "text" : "The pipeline finished",  "color": "#7CFC00" }] }'
        env:
          SLACK_WEBHOOK: ${{  secrets.SLACK_WEBHOOK }}
          GITHUB_WORKFLOW_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          CHANNEL_ID: ${{ github.event.client_payload.data.channel_id }}