name: Prepare for next day deployment

on:
  push:
    branches:
      - master

jobs:

  prepare-prod-deployment:
    name: Prepare for next day deployment
    runs-on: ubuntu-latest
    timeout-minutes: 85
    steps:
      - name: Tagging the build
        run: |
            mkdir ~/.ssh
            echo "1"
            touch ~/.ssh/known_hosts
            echo "2"
            ssh-keygen -R github.com
            echo "3"
            ssh-keyscan github.com >> $HOME/.ssh/known_hosts
            echo "4"
            ssh-add $HOME/.ssh/nhs-ci_rsa && cd ci-cd &&
            echo "5"
            echo ${git log --format="* %s. [Author %an]" prd..rc}
            echo "6"



