name: Prepare for next day deployment

on:
  schedule:
    # Runs at 3 pm weekdays (UK time)
    - cron: "*/5 * * * *"

jobs:

  prepare-prod-deployment:
    name: Prepare for next day deployment
    runs-on: ubuntu-latest
    timeout-minutes: 85
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Need all the tags for versioning

      - name: Slack message (List Jira Tickets to be released)
        if: ${{ success() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "${{ env.CHANNEL_ID }}", "text": "Pipeline Finished", "attachments": [{ "text" : "The pipeline finished",  "color": "#7CFC00" }] }'
        env:
          SLACK_WEBHOOK: ${{  secrets.SLACK_WEBHOOK }}
          GITHUB_WORKFLOW_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          CHANNEL_ID: ${{ github.event.client_payload.data.channel_id }}