name: Prepare for next day deployment

on:
  push:
    branches:
      - master

jobs:
  prepare-prod-deployment:
    name: Prepare for next day deployment -1
    runs-on: ubuntu-latest
    timeout-minutes: 85
    steps:

      - name: Show default environment variables
        run: |
          echo "The job_id is: "


      - name: Checkout (check this)
        id: githublist
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Need all the tags for versioning

      - name: GIT check
        run: |
          echo ${{ github.event.head_commit.message }}
          echo '--->'   $(git log --format="* %s. [Author %an]" uat..rc)

      - name: Slack message (List Jira Tickets to be released)
        if: ${{ success() }}
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ env.SLACK_WEBHOOK }}
          data: '{ "channel": "C04KERNBD4J", "text": "Release to production has been scheduled at 12:05 on the next working day. The following new changes (if any) will be released:", "attachments": [{ "text" : "The pipeline finished",  "color": "#7CFC00" }] }'
        env:
          SLACK_WEBHOOK: ${{  secrets.SLACK_WEBHOOK }}
          GITHUB_WORKFLOW_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          CHANNEL_ID: ${{ github.event.client_payload.data.channel_id }}