name: Prepare for next day deployment

on:
  push:
    branches:
      - master

jobs:

  prepare-prod-deployment:
    name: Prepare for next day deployment
    runs-on: ubuntu-latest
    timeout-minutes: 85
    steps:
      - name: Tagging the build
        run: |
            touch ~/.ssh/known_hosts
            ssh-keygen -R github.com
            ssh-keyscan github.com >> $HOME/.ssh/known_hosts
            git log --format="* %s. [Author %an]" prd..rc



