name: Prepare for next day deployment

on:
  push:
    branches:
      - master

jobs:

  prepare-prod-deployment:
    name: Prepare for next day deployment
    runs-on: ubuntu-latest
    timeout-minutes: 85
    steps:
      - name: Tagging the build
        run: |
          ssh-add $HOME/.ssh/nhs-ci_rsa && cd ci-cd &&
          git log --format="* %s. [Author %an]" prd..rc



