# This is a basic workflow to help you get started with Actions

name: Clear Builds

on:
  push:
    branches:
      - master
env:
  NO_OF_DISTRIBUTION_TO_KEEP_PROD: 40
  NO_OF_DISTRIBUTION_TO_KEEP_NON_PROD: 70

jobs:

  build:
    name: Clear Builds
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.remove-distribution.outputs.deven}}
      latestIds: ${{ steps.latest-distribution-id.outputs.latestId }}
      tokens: ${{steps.jwt_token.outputs.token}}
    timeout-minutes: 90

    steps:
      # Get API access token and verify it.
      - name: Obtaino JWT Token
        id: jwt_token
        run: |
          response=$(curl -i \
          -H "Accept: application/json; charset=utf-8" \
          -X POST https://api.${{ secrets.HOST }}/v3/authn/access_token \
          -d '{ "username": "${{ env.USERNAME }}", "password": "${{ env.PASSWORD }}" }')
          token=$(echo $response | awk 'match($0, /access_token":"[^"]+"/) {print substr($0, RSTART+15)}' | cut -d '"' -f 1 )
          refresh=$(echo $response | awk 'match($0, /refresh_token":"[^"]+"/) {print substr($0, RSTART+16)}' | cut -d '"' -f 1 )
          echo "::set-output name=token::$token"
          echo "::set-output name=refresh::$refresh"
        env:
          USERNAME: ${{ secrets.MISSION_CONTROL_API_USERNAME }}
          PASSWORD: ${{ secrets.MISSION_CONTROL_API_PASSWORD }}

      - name: Verify JWT Token
        id: jwt_token_verify
        run: |
          code=$(curl -L \
          -H "Accept: application/json; charset=utf-8" \
          -H "Authorization: Bearer ${{ steps.jwt_token.outputs.token }}" \
          -X GET https://api.${{ secrets.HOST }}/v3/authn/verify_token \
          -o /dev/null -w '%{http_code}\n' -s)
          echo "::set-output name=code::$code"

      - name: Check Response Code from Verify JWT Token
        if: ${{ steps.jwt_token_verify.outputs.code != 200 }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('The JWT token failed verification!')
        env:
          # 'CODE' is for debugging fails
          CODE: ${{ steps.jwt_token_verify.outputs.code }}

      #
      # Prepare App Config Deployment Details
      #
      - name: Get Distribution List
        id: distribution-list
        run: |
          response=$(curl \
          -H "Authorization: Bearer ${{ steps.jwt_token.outputs.token }}" \
          -X GET https://api.${{ secrets.HOST }}/v3/distributions)
          echo "::set-output name=matrix::${response}"

      - name: Get Latest Distribution Id Of Environment
        id: latest-distribution-id
        run: |
          latestId=$(echo '${{steps.distribution-list.outputs.matrix}}' | sed -e 's/+00:00/Z/g' | jq --compact-output '[.items[] | {id: .id , date: .createdAt, name: .name}] | sort_by(.date) | map(select(.name | test("^web"))) | map(.id) | .[:${{env.NO_OF_DISTRIBUTION_TO_KEEP_NON_PROD}}]')
          echo "::set-output name=latestId::${latestId}"


      - name: Remove old Distribution from Environment
        id: remove-distribution
        run: |
          distributionListL=$(echo '${{steps.distribution-list.outputs.matrix}}' | jq --compact-output '[.items[] | {id: .id , date: .createdAt} ]')
           JSON={\"include\":${distributionListL}}
          echo "::set-output name=deven::{\"include\":${distributionListL}}"

      - name: Print JSON
        id: print-json
        run: |
          echo "***********************"
          echo ${{steps.remove-distribution.outputs.deven}}
          echo "***********************"
          echo ${{steps.latest-distribution-id.outputs.latestId}}
          echo "***********************"

  remove-builds:
    name: Remove Builds
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix: ${{fromJson(needs.build.outputs.matrix)}}
      fail-fast: false
    if: ${{ contains(needs.build.outputs.latestIds , needs.build.outputs.matrix.id) }}
    steps:
     - name: Build is recent
       id: keep_build
       if: ${{ contains(needs.build.outputs.latestIds, matrix.id) }}
       run: |
         echo " Keep the build "
         echo "::set-output name=code::100"
     - name: Check if Build to be deleted
       id: remove_build
       if: ${{ ! contains(needs.build.outputs.latestIds, matrix.id) }}
       run: |
         code=$(curl \
         -H "Authorization: Bearer ${{ needs.build.outputs.tokens }}" \
         -X DELETE https://api.${{ secrets.HOST }}/v3/distributions/${{matrix.id}} \
         -o /dev/null -w '%{http_code}\n' -s)
         echo ${code}
         echo "::set-output name=code::$code"
     - name: Authentication failed
       if: ${{ steps.remove_build.outputs.code == 401 }}
       uses: actions/github-script@v3
       with:
         script: |
           core.setFailed(' 401 Authentication error' )
     - name: Removal of Build failed
       if: ${{ steps.keep_build.outputs.code != 100 && steps.remove_build.outputs.code != 200 }}
       uses: actions/github-script@v3
       with:
         script: |
           core.setFailed('Removal failed ')
