name: Scheduled Deployment of PROD (ODv2)

# Schedule deployment to Production
on:
  schedule:
    # Runs at 12:05 pm weekdays (UK time)
    - cron: "5 12 * * 1-5"

jobs:
  deploy-to-prod:
    #Calling Deploy to Production workflow
    uses: ./.github/workflows/deploy-to-production.yml
    with:
      prdFileName: "rc.tar.gz"
    secrets:
      HOST: ${{ secrets.HOST }}
      MISSION_CONTROL_API_USERNAME: ${{ secrets.MISSION_CONTROL_API_USERNAME }}
      MISSION_CONTROL_API_PASSWORD: ${{ secrets.MISSION_CONTROL_API_PASSWORD }}
  post-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Tagging the build
        run: |
          make git.update-environment-tag ENV=prd VERSION=rc