name: Slack Deployment of PROD Command for ODv2

on:
  push:
    branches:
      - master

jobs:
  deploy-to-prod:
    uses: Deven-Rawat/hippo/.github/workflows/deploy-to-production.yml@main
    with:
      username: "rc.tar.gz"