name: Slack Deployment of PROD Command for ODv2

on:
  push:
    branches:
      - master

jobs:
  deploy-to-prod:
    uses: ./.github/workflows/deploy-to-production.yml
    with:
      username: "rc.tar.gz"